# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
variables:
  buildConfiguration: 'Release'
stages:
 - script: dotnet build --configuration $(buildConfiguration)
   displayName: 'dotnet build $(buildConfiguration)'
 - task: DotNetCoreCLI@2
   inputs:
     command: 'publish'
     publishWebProjects: true
   jobs:
   - job: buildandtest
     pool:
      vmImage: ubuntu-latest
     steps:
  # deploy to Azure Web App staging
     - task: AzureWebApp@1
       inputs:
         azureSubscription: 'DevopsConnection'
         appType: 'webAppLinux'
         appName: 'serviceapp'
         deployToSlotOrASE: true
         resourceGroupName: <resource group name>
         slotName: 'staging'
         package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
     - task: AzureAppServiceManage@0
       inputs:
         azureSubscription: 'DevopsConnection'
         appType: webAppLinux
         WebAppName: 'dotnetwebapp'
         ResourceGroupName: 'MerazRG'
         SourceSlot: staging
         SwapWithProduction: true
   - job: deploy
     dependsOn: buildandtest
     condition: succeeded()

